---
title: "SEMANA 14"
author: "ARGUEDAS MARCOS"
format: html
editor: visual
---

##  SEMANA14 Realizar el análisis de regresión,análisis
 univariado,multivariado

```{r}
# Analisis Regresión Lineal Univariada en R
set.seed(123)
n <- 100
IMC <- rnorm(n, 27, 4)
PAS <- 90 + 1.5*IMC + rnorm(n, 0, 8)
datos <- data.frame(IMC, PAS)
head(datos)
```

```{r}
# # Ajustar modelo
modelo_uni <- lm(PAS ~ IMC, data = datos)
summary(modelo_uni)
```

```{r}
#Gráfico
plot(datos$IMC, datos$PAS, main="PAS vs IMC", xlab="IMC", ylab="PAS")
abline(modelo_uni, lwd=2)
```

```{r}
#Regresión Multivariada en R
set.seed(123)
n <- 120
IMC <- rnorm(n, 27, 4)
Edad <- rnorm(n, 45, 10)
Actividad <- rnorm(n, 3, 1)
# horas por semana
# Modelo real para generar datos
PAS <- 80 + 1.2*IMC + 0.6*Edad - 2.5*Actividad + rnorm(n, 0, 10)
datos2 <- data.frame(IMC, Edad, Actividad, PAS)
head(datos2)
```

```{r}
#Ajustar modelo múltiple
modelo_multi <- lm(PAS ~ IMC + Edad + Actividad, data = datos2)
summary(modelo_multi)
```

```{r}
#Comparar modelos
anova(modelo_uni, modelo_multi)
#Observación por que no se puede ejecutar
```

```{r}
# Diagnóstico del modelo (muy importante)
par(mfrow=c(2,2))
plot(modelo_multi)
```
